name: buildReleases

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
jobs:
  gradle:
    strategy:
      matrix:
        # os:  [windows-latest, macos-latest, ubuntu-latest]
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: install dependencies ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt install libcurl4-openssl-dev

      - id: gradle-native-build
        name: ./gradlew buildReleases
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: buildReleases
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
      - id: gradle-jvm-build
        name: ./gradlew runShadow
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: runShadow
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

      # Upload
      - id: upload-linux-artifact
        name: Upload Linux Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Linux Artifact
          path: 'build/native/linuxX64*/'
      - id: upload-macos-artifact
        name: Upload macOS Artifact
        uses: actions/upload-artifact@v3
        with:
          name: macOS Artifact
          path: 'build/native/macosX64*/'
      - id: upload-windows-artifact
        name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows Artifact
          path: 'build/native/mingwX64*/'
      - id: upload-jvm-artifact
        name: Upload JVM Artifact
        uses: actions/upload-artifact@v3
        with:
          name: JVM Artifact
          path: 'build/install/uniter-shadow'
